using System;
using System.Globalization;

namespace PIMS3.Helpers
{
    public class AppException: Exception
    {
        /* Notes: ============================
            A custom exception class used in differentiating handled vs. unhandled exceptions. 
            Handled exceptions   : generated by the application & used to display friendly error messages, e.g., business logic or validation exceptions.
            UnHandled exceptions : Generated by the .NET framework, via bugs in the application code.
        */
        
        // Ctors
        public AppException() : base()
        { }

        public AppException(string message) : base(message)
        { }

        public AppException(string message, params object[] args) : base(string.Format(CultureInfo.CurrentCulture, message,args))
        { }

    }
}
